apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
