apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
data:
  zoo.cfg: |
    tickTime={{ .Values.zookeeperConfig.tickTime | default 2000 }}
    initLimit={{ .Values.zookeeperConfig.initLimit | default 10 }}
    syncLimit={{ .Values.zookeeperConfig.syncLimit | default 5 }}
    dataDir={{ .Values.persistence.mountPath }}
    clientPort={{ .Values.service.port | default 2181 }}
    electionPortBindRetry=10

    {{- if .Values.metrics.enabled }}
    metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
    metricsProvider.httpHost=0.0.0.0
    metricsProvider.httpPort={{ .Values.metrics.service.port | default 7000 }}
    metricsProvider.exportJvmInfo=true
    {{- end }}