apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
data:
  zoo.cfg: |
    tickTime={{ .Values.zookeeperConfig.tickTime | default 2000 }}
    initLimit={{ .Values.zookeeperConfig.initLimit | default 10 }}
    syncLimit={{ .Values.zookeeperConfig.syncLimit | default 5 }}
    dataDir={{ .Values.persistence.mountPath }}
    clientPort={{ .Values.service.port | default 2181 }}
    electionPortBindRetry=10
