# Test values for extraVolumes and extraVolumeMounts feature
# This configuration adds an emptyDir volume for backup purposes

replicaCount: 1

# Minimal resource configuration for local testing
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Test extraVolumes - adding an emptyDir for backups
extraVolumes:
  - name: backup-volume
    emptyDir: {}
  - name: config-volume
    configMap:
      name: postgres-test-config
      optional: true

# Test extraVolumeMounts - mount the volumes in the container
extraVolumeMounts:
  - name: backup-volume
    mountPath: /backup
  - name: config-volume
    mountPath: /config
    readOnly: true

# Basic configuration
auth:
  username: testuser
  password: testpass
  database: testdb

persistence:
  enabled: true
  size: 1Gi
