apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.client }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.ports.client }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.service.ports.internal }}
      targetPort: internal
      protocol: TCP
      name: internal
    - port: {{ .Values.service.ports.controller }}
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
{{- if .Values.externalAccess.enabled }}
{{- $root := . }}
{{- range $i := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" $root }}-{{ $i }}-external
  namespace: {{ include "cloudpirates.namespace" $root }}
  labels:
    {{- include "kafka.labels" $root | nindent 4 }}
  {{- with $root.Values.externalAccess.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $root.Values.externalAccess.service.type }}
  {{- $host := include "kafka.externalAdvertisedHost" (dict "context" $root "ordinal" $i) }}
  {{- if and (eq $root.Values.externalAccess.service.type "LoadBalancer") (gt (len $root.Values.externalAccess.service.loadBalancerIPs) $i) }}
  loadBalancerIP: {{ $host }}
  {{- end }}
  publishNotReadyAddresses: false
  ports:
    - port: {{ $root.Values.externalAccess.service.ports.external }}
      targetPort: external
      protocol: TCP
      name: external
  selector:
    {{- include "kafka.selectorLabels" $root | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "kafka.fullname" $root }}-{{ $i }}
{{- end }}
{{- end }}
