{{- if not .Values.keycloak.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with (include "keycloak.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password: {{ default (.Values.keycloak.adminPassword | default (randAlphaNum 32) | b64enc) | quote }}
{{- end }}
---
{{- if and (not .Values.database.existingSecret) (or (eq .Values.database.type "postgres") (eq .Values.database.type "mysql") (eq .Values.database.type "mariadb")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "keycloak.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with (include "keycloak.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  db-username: {{ .Values.database.username | b64enc | quote }}
  db-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}