{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
  {{- with (include "memcached.annotations" .) }}
  annotations: 
{{- . | indent 4 }}
  {{- end }}
data:
  {{- if .Values.configMap.data }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- end }}
{{- end }}