apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
  {{- with (include "memcached.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "memcached.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "memcached.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
{{- with (include "memcached.imagePullSecrets" .) }}
{{ . | nindent 6 }}
{{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "memcached.serviceAccountName" . }}
      securityContext: {{ include "cloudpirates.renderPodSecurityContext" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          image: {{ include "memcached.image" . | quote }}
          imagePullPolicy: {{ include "cloudpirates.imagePullPolicy" (dict "image" .Values.image) }}
          args:
            {{- if .Values.config.memoryLimit }}
            - "-m"
            - {{ .Values.config.memoryLimit | quote }}
            {{- end }}
            {{- if .Values.config.maxConnections }}
            - "-c"
            - {{ .Values.config.maxConnections | quote }}
            {{- end }}
            {{- if .Values.config.verbosity }}
            - {{ printf "-%s" (repeat (.Values.config.verbosity | int) "v") | quote }}
            {{- end }}
            {{- range .Values.config.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
          {{- with .Values.extraEnvVars }}
          env:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: memcached
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: memcached
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ include "memcached.metrics.image" . | quote }}
          imagePullPolicy: {{ include "cloudpirates.imagePullPolicy" (dict "image" .Values.metrics.image) }}
          args:
            - "--memcached.address=localhost:{{ .Values.service.port }}"
            - "--web.listen-address=:{{ .Values.metrics.service.port }}"
            {{- range .Values.metrics.extraArgs }}
            - {{ . }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
          resources: {{ toYaml .Values.metrics.resources | nindent 12 }}
        {{- end }}
      {{- if .Values.extraVolumes }}
      volumes:
        {{- toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
