apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}