apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
  {{- with (include "memcached.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}-metrics
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- $annotations := merge .Values.metrics.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}
{{- end }}
