{{- if and .Values.config.content (not .Values.config.existingConfigmap)}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with (include "redis.annotations" .) }}
  annotations: 
{{- . | indent 4 }}
  {{- end }}
data:
  redis.conf: |
    {{- .Values.config.content | nindent 4 }}
{{- end }}