{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with (include "redis.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Redis client connections
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels: {}
      {{- end }}
    {{- if and (eq .Values.architecture "replication") (not .Values.sentinel.enabled) }}
    # Allow Redis replica-to-master communication
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              {{- include "redis.selectorLabels" . | nindent 14 }}
    {{- end }}
    {{- if .Values.sentinel.enabled }}
    # Allow Sentinel connections
    - ports:
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels: {}
      {{- end }}
    # Allow Sentinel-to-Redis communication
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              {{- include "redis.sentinel.selectorLabels" . | nindent 14 }}
    # Allow Sentinel peer communication
    - ports:
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              {{- include "redis.sentinel.selectorLabels" . | nindent 14 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    # Allow metrics scraping
    - ports:
        - port: {{ .Values.metrics.service.port }}
          protocol: TCP
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      {{- end }}
    {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if and (eq .Values.architecture "replication") (not .Values.sentinel.enabled) }}
    # Allow Redis replica-to-master communication
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "redis.selectorLabels" . | nindent 14 }}
    {{- end }}
    {{- if .Values.sentinel.enabled }}
    # Allow Redis-to-Sentinel communication
    - ports:
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "redis.sentinel.selectorLabels" . | nindent 14 }}
    # Allow Sentinel-to-Redis communication
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "redis.selectorLabels" . | nindent 14 }}
    # Allow Sentinel peer communication
    - ports:
        - port: {{ .Values.sentinel.port }}
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              {{- include "redis.sentinel.selectorLabels" . | nindent 14 }}
    {{- end }}
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
