{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nginx.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- if .Values.networkPolicy.allowExternal }}
    - {}
    {{- else }}
    {{- range .Values.networkPolicy.ingressRules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- range .Values.networkPolicy.egressRules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}