{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "valkey.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "valkey.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.serviceAccount.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken | default false }}
{{- end }}