apiVersion: v2
name: timescaledb
description: TimescaleDB - The Open Source Time-Series Database for PostgreSQL
type: application
version: 0.4.0
appVersion: "2.22.0-pg17"
keywords:
  - timescaledb
  - timeseries
  - postgresql
  - database
  - sql
  - analytics
home: https://www.timescale.com
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/timescaledb
  - https://github.com/timescale/timescaledb
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/b2e01452ce/timescaledb-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: TimescaleDB
      url: https://www.timescale.com
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/timescaledb
    - name: Application
      url: https://github.com/timescale/timescaledb
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: added
          description: "[universal] use a string instead of a boolean"
          links:
            - name: "PR #413"
              url: "https://github.com/CloudPirates-io/helm-charts/pull/413"
