## @section Global parameters
global:
  ## @param global.imageRegistry Global Docker Image registry
  imageRegistry: ""
  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  imagePullSecrets: []

## @section Common parameters
## @param nameOverride String to partially override minio.fullname
nameOverride: ""
## @param fullnameOverride String to fully override minio.fullname
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
commonAnnotations: {}

## @section MinIO image configuration
image:
  ## @param image.registry MinIO image registry
  registry: docker.io
  ## @param image.repository MinIO image repository
  repository: minio/minio
  ## @param image.tag MinIO image tag (immutable tags are recommended)
  tag: "RELEASE.2025-09-07T16-13-09Z@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e"
  ## @param image.imagePullPolicy MinIO image pull policy
  imagePullPolicy: Always

## @section MinIO Authentication
auth:
  ## @param auth.rootUser MinIO root username
  rootUser: "admin"
  ## @param auth.rootPassword MinIO root password. If not set, a random password will be generated
  rootPassword: ""
  ## @param auth.existingSecret Name of existing secret containing MinIO credentials
  existingSecret: ""
  ## @param auth.existingSecretUserKey Key in existing secret containing username
  existingSecretUserKey: "user"
  ## @param auth.existingSecretPasswordKey Key in existing secret containing password
  existingSecretPasswordKey: "password"

## @section MinIO configuration
config:
  ## @param config.region MinIO server default region
  region: ""
  ## @param config.browserEnabled Enable MinIO web browser
  browserEnabled: true
  ## @param config.domain MinIO server domain
  domain: ""
  ## @param config.serverUrl MinIO server URL for console
  serverUrl: ""
  ## @param config.extraEnvVars Extra environment variables to be set on MinIO containers
  extraEnvVars: []

## @section Deployment configuration
replicaCount: 1

## @section Pod annotations and labels
podAnnotations: {}
podLabels: {}

## @section Security Context
podSecurityContext:
  ## @param podSecurityContext.fsGroup Group ID for the volumes of the pod
  fsGroup: 1001

securityContext:
  ## @param securityContext.allowPrivilegeEscalation Enable container privilege escalation
  allowPrivilegeEscalation: false
  ## @param securityContext.runAsNonRoot Configure the container to run as a non-root user
  runAsNonRoot: true
  ## @param securityContext.runAsUser User ID for the MinIO container
  runAsUser: 1001
  ## @param securityContext.runAsGroup Group ID for the MinIO container
  runAsGroup: 1001
  ## @param securityContext.readOnlyRootFilesystem Mount container root filesystem as read-only
  readOnlyRootFilesystem: true
  ## @param securityContext.capabilities.drop Linux capabilities to be dropped
  capabilities:
    drop:
      - ALL

## @section Service configuration
service:
  ## @param service.type MinIO service type
  type: ClusterIP
  ## @param service.port MinIO service port
  port: 9000
  ## @param service.consolePort MinIO console service port
  consolePort: 9090
  ## @param service.annotations Service annotations
  annotations: {}

## @section Ingress configuration
ingress:
  ## @param ingress.enabled Enable ingress record generation for MinIO
  enabled: false
  ## @param ingress.className IngressClass that will be used to implement the Ingress
  className: ""
  ## @param ingress.annotations Additional annotations for the Ingress resource
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  ## @param ingress.hosts[0].host Hostname for MinIO ingress
  ## @param ingress.hosts[0].paths[0].path Path for MinIO ingress
  ## @param ingress.hosts[0].paths[0].pathType Path type for MinIO ingress
  hosts:
    - host: minio.local
      paths:
        - path: /
          pathType: Prefix
  ## @param ingress.tls TLS configuration for MinIO ingress
  tls: []
  #  - secretName: minio-tls
  #    hosts:
  #      - minio.local

## @section Console Ingress configuration
consoleIngress:
  ## @param consoleIngress.enabled Enable ingress record generation for MinIO Console
  enabled: false
  ## @param consoleIngress.className IngressClass that will be used to implement the Ingress
  className: ""
  ## @param consoleIngress.annotations Additional annotations for the Console Ingress resource
  annotations:
    {}
    # nginx.ingress.kubernetes.io/proxy-body-size: 1000m
  ## @param consoleIngress.hosts[0].host Hostname for MinIO Console ingress
  ## @param consoleIngress.hosts[0].paths[0].path Path for MinIO Console ingress
  ## @param consoleIngress.hosts[0].paths[0].pathType Path type for MinIO Console ingress
  hosts:
    - host: minio-console.local
      paths:
        - path: /
          pathType: Prefix
  ## @param consoleIngress.tls TLS configuration for MinIO Console ingress
  tls: []

## @section Resources
resources:
  {}
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## @section Persistence
persistence:
  ## @param persistence.enabled Enable persistence using Persistent Volume Claims
  enabled: true
  ## @param persistence.storageClass Persistent Volume storage class
  storageClass: ""
  ## @param persistence.annotations Persistent Volume Claim annotations
  annotations: {}
  ## @param persistence.size Persistent Volume size
  size: 8Gi
  ## @param persistence.accessModes Persistent Volume access modes
  accessModes:
    - ReadWriteOnce
  ## @param persistence.existingClaim The name of an existing PVC to use for persistence
  existingClaim: ""
  ## @param mountPath The path where to mount the data volume
  mountPath: /mnt/data

## @section Liveness and readiness probes
livenessProbe:
  ## @param livenessProbe.enabled Enable livenessProbe on MinIO containers
  enabled: true
  ## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  initialDelaySeconds: 30
  ## @param livenessProbe.periodSeconds Period seconds for livenessProbe
  periodSeconds: 10
  ## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  timeoutSeconds: 5
  ## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
  failureThreshold: 3
  ## @param livenessProbe.successThreshold Success threshold for livenessProbe
  successThreshold: 1

readinessProbe:
  ## @param readinessProbe.enabled Enable readinessProbe on MinIO containers
  enabled: true
  ## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  initialDelaySeconds: 5
  ## @param readinessProbe.periodSeconds Period seconds for readinessProbe
  periodSeconds: 5
  ## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  timeoutSeconds: 3
  ## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
  failureThreshold: 3
  ## @param readinessProbe.successThreshold Success threshold for readinessProbe
  successThreshold: 1

startupProbe:
  ## @param startupProbe.enabled Enable startupProbe on MinIO containers
  enabled: false
  ## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  initialDelaySeconds: 10
  ## @param startupProbe.periodSeconds Period seconds for startupProbe
  periodSeconds: 10
  ## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
  timeoutSeconds: 5
  ## @param startupProbe.failureThreshold Failure threshold for startupProbe
  failureThreshold: 30
  ## @param startupProbe.successThreshold Success threshold for startupProbe
  successThreshold: 1

## @section Node Selection
nodeSelector: {}

tolerations: []

affinity: {}

## @param extraObjects Array of extra objects to deploy with the release
extraObjects: []
