{{- if not .Values.config.control.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phpmyadmin.fullname" . }}-control
  namespace: {{ include "phpmyadmin.namespace" . }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" (include "phpmyadmin.namespace" .) (printf "%s-control" (include "phpmyadmin.fullname" .))) }}
  {{- $existingPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingPassword = index $existingSecret.data "password" }}
  {{- end }}
  password: {{ $existingPassword | default (.Values.config.control.password | default (randAlphaNum 32) | b64enc) | quote }}
{{- end }}
