{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openldap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.existingSecretPasswordKey }}: {{ .Values.auth.adminPassword | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}
