{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "rustfs.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "rustfs.fullname" .)) }}
  {{- $existingSecretKey := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingSecretKey = index $existingSecret.data "secret-key" }}
  {{- end }}
  access-key: {{ .Values.auth.accessKey | b64enc | quote }}
  secret-key: {{ $existingSecretKey | default (.Values.auth.secretKey | default (randAlphaNum 32) | b64enc) | quote }}
{{- end }}