apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- $annotations := merge .Values.service.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: api
      targetPort: api
    - port: {{ .Values.service.consolePort }}
      protocol: TCP
      name: console
      targetPort: console
  selector:
    {{- include "rustfs.selectorLabels" . | nindent 4 }}