{{- $numPolicies := len .Values.setup.policies }}
{{- $numBuckets := len .Values.setup.buckets }}
{{- $numUsers := len .Values.setup.users }}
{{- if or (gt $numPolicies 0) (gt $numBuckets 0) (gt $numUsers 0) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rustfs.fullname" . }}-setup-{{ randAlpha 5 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "rustfs.annotations" . | nindent 4 }}
  {{- end }}
spec:
  template:
    spec:
      serviceAccountName: {{ template "rustfs.serviceAccountName" . }}
      securityContext: {{ include "cloudpirates.renderPodSecurityContext" . | nindent 8 }}
      restartPolicy: OnFailure
      volumes:
        - name: setup
          secret:
            {{- if .Values.setup.existingSecret }}
            secretName: {{ .Values.setup.existingSecret }}
            {{- else }}
            secretName: {{ include "rustfs.fullname" . }}-setup
            {{- end }}
      initContainers:
        - name: waiting-for-service
          image: {{ include "rustfs-setup.image" . }}
          imagePullPolicy: {{ .Values.setup.image.imagePullPolicy }}
          env:
            - name: TIMEOUT
              value: "90"
            - name: HOST
              value: {{ include "rustfs.fullname" . }}
            - name: PORT
              value: {{ .Values.service.port | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              PORT="${PORT:-5432}"
              TIMEOUT="${TIMEOUT:-60}"
              INTERVAL="${INTERVAL:-2}"

              echo "Waiting for ${HOST}:${PORT} (with timeout: ${TIMEOUT}s)"

              START=$(date +%s)

              while true; do
                if nc -z "${HOST}" "${PORT}" >/dev/null 2>&1; then
                  echo "✅ ${HOST}:${PORT} available"
                  exit 0
                fi

                NOW=$(date +%s)
                if [ $((NOW - START)) -ge "${TIMEOUT}" ]; then
                  echo "❌ Timeout reached"
                  exit 1
                fi

                sleep "$INTERVAL"
              done
      containers:
        - name: setup
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          image: {{ include "rustfs-setup.image" . }}
          imagePullPolicy: {{ .Values.setup.image.imagePullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              rc alias set local "http://${RUSTFS_HOST}:${RUSTFS_PORT}" "${RUSTFS_ACCESS_KEY}" "${RUSTFS_SECRET_KEY}"

              yq e '.[]' /setup/policies | while read -r policy; do
                name=$(echo "${policy}" | yq e '.name')
                echo "${policy}" | yq e '.spec' -o=json > /tmp/policy.json
                cat /tmp/policy.json

                rc admin policy create local "${name}" /tmp/policy.json
              done

              yq e '.[]' setup/users | while read -r user; do
                name=$(echo "${user}" | yq e '.name')
                password=$(echo "${user}" | yq e '.password')
                policies=$(echo "${user}" | yq e '.policies[]')

                rc admin user add local "${name}" "${password}"

                echo ${policies} | while read e policy; do
                  rc admin policy attach local "${policy}" --user "${name}"
                done
              done

              yq e '.[]' setup/buckets | while read -r bucket; do
                name=$(echo "${bucket}" | yq e '.name')

                rc mb "local/${bucket}"
              done
          volumeMounts:
            - mountPath: /setup
              name: setup
          env:
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustfs.secretName" . }}
                  key: {{ include "rustfs.accessKeyKey" . }}
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustfs.secretName" . }}
                  key: {{ include "rustfs.secretKeyKey" . }}
            - name: RUSTFS_HOST
              value: {{ include "rustfs.fullname" . }}
            - name: RUSTFS_PORT
              value: {{ .Values.service.port | quote }}
{{- end }}
