apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
data:
  config.production.json: |-
    {
      "url": {{ printf "https://%s" (first .Values.ingress.hosts).host | quote }},
      "database": {
        {{- if .Values.mariadb.enabled }}
        "client": "mysql",
        "connection": {
          "host": "{{ include "ghost.fullname" . }}-mariadb",
          "port": {{ .Values.mariadb.service.port }},
          "user": {{ .Values.mariadb.auth.username | quote }},
          "password": {{ .Values.mariadb.auth.password | quote }},
          "database": {{ .Values.mariadb.auth.database | quote }}
        },
        {{- else }}
        "client": {{ .Values.config.database.client | quote }},
        "connection": {
          "host": {{ .Values.config.database.externalConnection.host | quote }},
          "port": {{ .Values.config.database.externalConnection.port }},
          "user": {{ .Values.config.database.externalConnection.user | quote }},
          "password": {{ .Values.config.database.externalConnection.password | quote }},
          "database": {{ .Values.config.database.externalConnection.database | quote }}
        },
        {{- end }}
        "pool": {
          "min": {{ .Values.config.database.pool.min }},
          "max": {{ .Values.config.database.pool.max }}
        }
      },
      "mail": {
        "transport": {{ .Values.config.mail.transport | quote }},
        "options": {
          "service": {{ .Values.config.mail.options.service | quote }},
          "host": {{ .Values.config.mail.options.host | quote }},
          "port": {{ .Values.config.mail.options.port }},
          "secure": {{ .Values.config.mail.options.secure }},
          "auth": {
            "user": {{ .Values.config.mail.options.auth.user | quote }},
            "pass": {{ .Values.config.mail.options.auth.pass | quote }}
          }
        },
        "from": {{ .Values.config.mail.from | quote }}
      },
      "admin": {
        "url": {{ printf "https://%s" (index .Values.ingress.hosts 1).host | quote }}
      },
      "server": {
        "host": {{ .Values.config.server.host | quote }},
        "port": {{ .Values.config.server.port }}
      },
      "privacy": {
        "useUpdateCheck": {{ .Values.config.privacy.useUpdateCheck }},
        "useGravatar": {{ .Values.config.privacy.useGravatar }},
        "useRpcPing": {{ .Values.config.privacy.useRpcPing }},
        "useStructuredData": {{ .Values.config.privacy.useStructuredData }}
      },
      "security": {
        "staffDeviceVerification": {{ .Values.config.security.staffDeviceVerification }}
      },
      "paths": {
        "contentPath": {{ .Values.config.paths.contentPath | quote }}
      },
      "referrerPolicy": {{ .Values.config.referrerPolicy | quote }},
      "logging": {
        "path": {{ .Values.config.logging.path | quote }},
        "useLocalTime": {{ .Values.config.logging.useLocalTime }},
        "level": {{ .Values.config.logging.level | quote }},
        "rotation": {
          "enabled": {{ .Values.config.logging.rotation.enabled }},
          "count": {{ .Values.config.logging.rotation.count }},
          "period": {{ .Values.config.logging.rotation.period | quote }}
        },
        "transports": {{ .Values.config.logging.transports | toJson }}
      },
      "caching": {
        "frontend": { "maxAge": {{ .Values.config.caching.frontend.maxAge }} },
        "contentAPI": { "maxAge": {{ .Values.config.caching.contentAPI.maxAge }} },
        "robotstxt": { "maxAge": {{ .Values.config.caching.robotstxt.maxAge }} },
        "sitemap": { "maxAge": {{ .Values.config.caching.sitemap.maxAge }} },
        "sitemapXSL": { "maxAge": {{ .Values.config.caching.sitemapXSL.maxAge }} },
        "wellKnown": { "maxAge": {{ .Values.config.caching.wellKnown.maxAge }} },
        "cors": { "maxAge": {{ .Values.config.caching.cors.maxAge }} },
        "publicAssets": { "maxAge": {{ .Values.config.caching.publicAssets.maxAge }} },
        "301": { "maxAge": {{ .Values.config.caching.threeHundredOne.maxAge }} },
        "customRedirects": { "maxAge": {{ .Values.config.caching.customRedirects.maxAge }} }
      },
      "compress": {{ .Values.config.compress }},
      "imageOptimization": {
        "resize": {{ .Values.config.imageOptimization.resize }}
      },
      "portal": {
        "url": {{ .Values.config.portal.url | quote }}
      },
      "sodoSearch": {
        "url": {{ .Values.config.sodoSearch.url | quote }},
        "styles": {{ .Values.config.sodoSearch.styles | quote }}
      },
      "comments": {
        "url": {{ .Values.config.comments.url | quote }},
        "styles": {{ .Values.config.comments.styles | quote }}
      },
      "enableDeveloperExperiments": {
        "enableDeveloperExperiments": false
      }
    }
