apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
  {{- with (include "ghost.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "ghost.selectorLabels" . | nindent 4 }}