global:
  imageRegistry: ""
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}


zookeeperConfig:
  tickTime: 2000
  initLimit: 10
  syncLimit: 5

image:
  registry: docker.io
  repository: zookeeper
  tag: "3.9.3@sha256:9980cafbff742c15b339811ae829faa61c69154606ec504223560da9d31acd43"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 2181

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi
  mountPath: /bitnami/zookeeper
  annotations: {}

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}
priorityClassName: ""
tolerations: []
affinity: {}

containerSecurityContext:
  runAsUser: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false

podSecurityContext:
  fsGroup: 1001

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

extraEnv: []
extraVolumes: []
extraVolumeMounts: []
extraObjects: []
