{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clusterpirate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{- include "clusterpirate.annotations" . | indent 4 }}
  {{- end }}
  labels:
    {{- include "clusterpirate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clusterpirate.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "clusterpirate.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}