{{- if and .Values.galera.enabled .Values.galera.sst.password (not .Values.galera.sst.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-galera
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.galera.sst.user }}
  {{ .Values.galera.sst.secretKeys.userKey }}: {{ .Values.galera.sst.user | b64enc | quote }}
  {{- end }}
  {{ .Values.galera.sst.secretKeys.passwordKey }}: {{ .Values.galera.sst.password | b64enc | quote }}
{{- end }}