name: Auto-label issues
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Apply labels
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            const section = (body.split(/### Affected helm charts/)[1] || "").trim();
            const labels = section.split(",").map(s => s.trim()).filter(Boolean);
            if (labels.length) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels
              });
            }
