name: Auto-label issues
on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Apply labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = (context.payload.issue.body.split(/### Affected Helm charts/)[1] || "")
              .trim()
              .split(",")
              .map((s) => s.trim())
              .filter((s) => s && s !== "_No response_")
            if (labels.length) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels,
              });
            }
