name: Auto-label issues
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Apply labels
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            const section = body.split(/### Affected helm charts/)[1] || "";
            const regex = /^- (.+)$/gim;
            const labels = [];
            let match;
            while ((match = regex.exec(section)) !== null) {
              labels.push(match[1].trim());
            }

            if (labels.length) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels
              });
            }
