name: Check signed commits in PR
on: pull_request_target

jobs:
  check-signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
        with:
          comment: |
            ## ⚠️ Unsigned Commits Detected

            This pull request contains unsigned commits.

            ### What does this mean?

            Signed commits help ensure the authenticity and traceability of contributions. They allow us to verify that commits actually came from the stated author, even if GitHub accounts are deleted or modified in the future.

            ### Current Policy (Grace Period)

            **This is currently a warning only.** We are in a transition period to give all contributors time to set up commit signing.

            After this grace period, **all commits will be required to be signed** before PRs can be merged.

            ### How to sign your commits

            Please see our [Contributing Guide](../blob/main/CONTRIBUTING.md#setting-up-your-development-environment) for detailed instructions on setting up commit signing.

            ### Resources

            - [Contributing Guide: Development Setup](../blob/main/CONTRIBUTING.md#setting-up-your-development-environment)
            - [GitHub Docs: About Commit Signature Verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)

            ---

            _This check will become mandatory in the future. Please start signing your commits now to avoid issues later._
