name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        id: chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_upload: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload chart
        env:
          CHANGED_CHARTS: ${{ steps.chart-releaser.outputs.changed_charts }}
          CHART_VERSION: ${{ steps.chart-releaser.outputs.chart_version }}
        run: |
          echo "CHANGED_CHARTS: $CHANGED_CHARTS"
          echo "CHART_VERSION: $CHART_VERSION"
          echo "DEBUG Running: helm registry login --username ${{ secrets.REGISTRY_USER }} --password ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}"
          # helm registry login --username ${{ secrets.REGISTRY_USER }} --password ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY }}
